# Site settings
# in the templates available like {{ site.myvariable }}.
title: ModellistaIT
email: dm@emanuela.info
brand: Emanuela De Munari
shop: "https://www.etsy.com/shop/ModellistaIT"
headline: ModellistaIT
description: > # this means to ignore newlines until "baseurl:"
  Modellista & sarta
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://emanuela.info" # the base hostname & protocol for your site
copyright:
  year: 2017
  message: All Rights Reserved

# Build settings
markdown: kramdown

# Account ids
snapwidget: 951600

# Contacts
email: dm@emanuela.info
phone: +39 3772479874 +39 3480137944
instagram: modellistait
facebook: ModellistaIT
etsy: ModellistaIT

# Tracking
googleAnalitycsID: UA-103821879-1
