# Site settings
role: ModellistaIT
name: "Emanuela De Munari"
description: "Modellista & sarta"
url: ""


# Delete the lines you don't need
# about 5 elements are recomended
facebook_username: ModellistaIT
instagram_username: modellistait
email: dm@emanuela.info
phone: +393480137944


avatar: yes
#avatar_img_path: "imgs/avatar.png"
# You can link to your GitHub image. That way it will get updated
# automatically whenever you change your GitHub profile picture
avatar_img_path: "https://avatars.githubusercontent.com/u/30652534"


front_img: yes
front_img_path: "imgs/background.jpg"
#front_img_path: "https://external.url/image.jpg"


favicon_img: yes
favicon_img_path: "imgs/favicon.ico"
#favicon_img_path: "https://external.url/favicon.ico"


# Build settings
markdown: kramdown
permalink: pretty


# Tracking
googleAnalitycsID: UA-103821879-1
